### ISSUE TITLE
Implement OPTIONS Server Method

### ISSUE THREAD

**Issue by DavidTPate** [5Sigma/celerity#54]
The OPTIONS server method should be implemented, the main use case I've run into in the past is for the pre-flight OPTIONS calls for CORs made by browsers.

**Comment by ViaoV** [comment]
There is a middleware handler for CORS preflight. Is there any reason to implement it on the route level too?

https://celerity.5sigma.io/middleware/cors/

**Comment by DavidTPate** [comment]
That's a good question. I'm not aware of any other uses for the `OPTIONS` HTTP method than for the Preflight CORS call. Looking through [RFC-2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) it just mentions:

> The response body, if any, SHOULD also include information about the communication options. The format for such a body is not defined by this specification, but might be defined by future extensions to HTTP.

Given that the only reason I could see is if we want a consumer of a library to be able to make their own CORS middleware which is a nice-to-have in my opinion.

So, I'm going to close this. Please re-open or comment if you disagree.
